title: Asteroseismology of early type stars
description: Tutorial given at the MESA summer school of 2023 on asteroseismology of early type stars.
authors: Created by May G. Pedersen, Mathias Michielsen, Lynn Buchele, and Jan Henneco.
remote_theme: pages-themes/slate@v0.2.0

url: https://michielsenm.github.io/mesa-summer-school-2023/
aux_links:
  Template Repository: https://github.com/MichielsenM/mesa-summer-school-2023
